// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(_grunt) {
    _grunt.initConfig({
      coffee: {
        filesOne: {
          expand: true,
          cwd: 'Public/coffees/',
          src: ['**/*.coffee'],
          dest: 'Public/js/',
          ext: '.js'
        }
      }
    });
    _grunt.loadNpmTasks('grunt-contrib-coffee');
    return _grunt.registerTask('default', ['coffee']);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
